// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcJcpG_7ofSFmxpVpN4VRP0_B09FwQSbc',
    appId: '1:604124824461:web:5791c7bdbe22ea5d4e73c4',
    messagingSenderId: '604124824461',
    projectId: 'safeher-2f759',
    authDomain: 'safeher-2f759.firebaseapp.com',
    databaseURL: 'https://safeher-2f759-default-rtdb.firebaseio.com',
    storageBucket: 'safeher-2f759.appspot.com',
    measurementId: 'G-9QHWT05SWS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN7X69xhCB_Sknn5R9bD-aRw-n8a8tOS0',
    appId: '1:604124824461:android:ebb160b2a83595224e73c4',
    messagingSenderId: '604124824461',
    projectId: 'safeher-2f759',
    databaseURL: 'https://safeher-2f759-default-rtdb.firebaseio.com',
    storageBucket: 'safeher-2f759.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2Uc69ZcNKt6gQRvmsh6JA5bFY0twSFQ0',
    appId: '1:604124824461:ios:c6fc274cf4097a974e73c4',
    messagingSenderId: '604124824461',
    projectId: 'safeher-2f759',
    databaseURL: 'https://safeher-2f759-default-rtdb.firebaseio.com',
    storageBucket: 'safeher-2f759.appspot.com',
    iosBundleId: 'com.example.mvp',
  );
}
